WebApplicationrRecolte/Models/historique_asscociation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationrRecolte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historique_asscociation
    {
        public int ID_histoAssoc { get; set; }
        public int ID_association { get; set; }
        public Nullable<System.DateTime> DATE_desactive { get; set; }
    
        public virtual association association { get; set; }
    }
}

WebApplicationrRecolte/Controllers/historique_asscociationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationrRecolte.Models;

namespace WebApplicationrRecolte.Controllers
{
    public class historique_asscociationController : Controller
    {
        private RecolteEntities db = new RecolteEntities();

        // GET: historique_asscociation
        public ActionResult Index()
        {
            var historique_asscociation = db.historique_asscociation.Include(h => h.association);
            return View(historique_asscociation.ToList());
        }

        // GET: historique_asscociation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            historique_asscociation historique_asscociation = db.historique_asscociation.Find(id);
            if (historique_asscociation == null)
            {
                return HttpNotFound();
            }
            return View(historique_asscociation);
        }

        // GET: historique_asscociation/Create
        public ActionResult Create()
        {
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association");
            return View();
        }

        // POST: historique_asscociation/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_histoAssoc,ID_association,DATE_desactive")] historique_asscociation historique_asscociation)
        {
            if (ModelState.IsValid)
            {
                db.historique_asscociation.Add(historique_asscociation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", historique_asscociation.ID_association);
            return View(historique_asscociation);
        }

        // GET: historique_asscociation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            historique_asscociation historique_asscociation = db.historique_asscociation.Find(id);
            if (historique_asscociation == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", historique_asscociation.ID_association);
            return View(historique_asscociation);
        }

        // POST: historique_asscociation/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_histoAssoc,ID_association,DATE_desactive")] historique_asscociation historique_asscociation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(historique_asscociation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", historique_asscociation.ID_association);
            return View(historique_asscociation);
        }

        // GET: historique_asscociation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            historique_asscociation historique_asscociation = db.historique_asscociation.Find(id);
            if (historique_asscociation == null)
            {
                return HttpNotFound();
            }
            return View(historique_asscociation);
        }

        // POST: historique_asscociation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            historique_asscociation historique_asscociation = db.historique_asscociation.Find(id);
            db.historique_asscociation.Remove(historique_asscociation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationrRecolte/Views/historique_asscociation/Create.cshtml
@model WebApplicationrRecolte.Models.historique_asscociation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>historique_asscociation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_association, "ID_association", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_association", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_association, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_desactive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_desactive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATE_desactive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationrRecolte/Views/historique_asscociation/Delete.cshtml
@model WebApplicationrRecolte.Models.historique_asscociation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>historique_asscociation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATE_desactive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_desactive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.association.NOM_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.association.NOM_association)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplicationrRecolte/Views/historique_asscociation/Details.cshtml
@model WebApplicationrRecolte.Models.historique_asscociation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Details</h2>

<div>
    <h4>historique_asscociation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATE_desactive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_desactive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.association.NOM_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.association.NOM_association)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_histoAssoc }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationrRecolte/Views/historique_asscociation/Edit.cshtml
@model WebApplicationrRecolte.Models.historique_asscociation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>historique_asscociation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_histoAssoc)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_association, "ID_association", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_association", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_association, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_desactive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_desactive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATE_desactive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationrRecolte/Views/historique_asscociation/Index.cshtml
@model IEnumerable<WebApplicationrRecolte.Models.historique_asscociation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="main-panel">
    <div class="container">

        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-3">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h2 class="text-white pb-2 fw-bold">
                            HISTORIQUE  DES ASSOCIATIONS</
                            h2>
</div>
                    <div class="ml-md-auto py-2 py-md-0">
                        <!-- PAGE-HEADER -->
                        <div class="page-header">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">HISTORIQUE  DES ASSOCIATIONS</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Liste
                                </li>
                            </ol>
                        </div>
                        <!-- PAGE-HEADER END -->
                    </div>
                </div>
            </div>
        </div>


        <div class="container-fluid">
            <a href="@Url.Action("create","historique_asscociation")" class=" btn btn-sm  btn-success pull-right  " style="margin-top:5px; margin-bottom:5px"><i class="fa fa-plus mr-2"></i>Désactive une association</a>
            <table class="table table-bordered">
                <tr>
                    <th>NOM</th>
                    <th>TEL</th>
                    <th> DATE DE CREATION</th>
                    <th> DATE DE DESACTIVATION</th>
                    <th>ETAT</th>
                    <th>OPTIONS</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.association.NOM_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.association.TEL_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.association.DATE_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DATE_desactive)
                        </td>
                        <td>
                            Inactif
                        </td>
                        <td>
                            <div class="dropdown">
                                <span class="dropdown-toggle dropdown-bg btn btn-outline-primary" role="button" id="dropdownMenuButton5"
                                      data-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </span>
                                <div class="dropdown-menu dropdown-menu-right shadow-none" aria-labelledby="dropdownMenuButton5">
                                    @Html.ActionLink("Modifier", "Details", new { id = item.ID_histoAssoc }, new { @class = "btn btn-sm btn-success " })
                                    @Html.ActionLink("Active", "Delete", new { id = item.ID_histoAssoc }, new { @class = "btn btn-sm btn-danger" })
                                </div>
                            </div>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>