WebApplicationrRecolte/Models/association.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationrRecolte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class association
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public association()
        {
            this.clients = new HashSet<client>();
            this.employe_association = new HashSet<employe_association>();
            this.historique_asscociation = new HashSet<historique_asscociation>();
        }
    
        public int ID_association { get; set; }
        public int ID_colline { get; set; }
        public string NOM_association { get; set; }
        public string TEL_association { get; set; }
        public Nullable<System.DateTime> DATE_association { get; set; }
    
        public virtual colline colline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employe_association> employe_association { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique_asscociation> historique_asscociation { get; set; }
    }
}

WebApplicationrRecolte/Controllers/associationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationrRecolte.Models;
using Highsoft.Web.Mvc.Charts;


namespace WebApplicationrRecolte.Controllers
{
    public class associationsController : Controller
    {
        private RecolteEntities db = new RecolteEntities();

       
        // GET: associations

        public ActionResult Indexe()
        {
            var association = db.associations.Include(a => a.colline);
            var historique = db.historique_asscociation;
            ViewData["association"] = association.ToList();
            ViewData["historique"] = historique.ToList();
            return View();
        }
        public ActionResult Index()
        {
            //var associations = db.associations.Include(a => a.colline);
            //return View(associations.ToList());
            var association = db.associations.Include(a => a.colline);
            var historique = db.historique_asscociation;
            ViewData["association"] = association.ToList();
            ViewData["historique"] = historique.ToList();
            return View();
        }
        // GET: associations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            association association = db.associations.Find(id);
            if (association == null)
            {
                return HttpNotFound();
            }
            return View(association);
        }

        // GET: associations/Create
        public ActionResult Create()
        {
            ViewBag.ID_province = new SelectList(db.provinces, "ID_province", "NOM_province");
            ViewBag.ID_commune = new SelectList(db.communes, "ID_commune", "NOM_commune");
            ViewBag.ID_zone = new SelectList(db.zones, "ID_zone", "NOM_zone");
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline");
            return View();
        }

        // POST: associations/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_association,ID_colline,NOM_association,TEL_association,DATE_association")] association association)
        {
            if (ModelState.IsValid)
            {
                db.associations.Add(association);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", association.ID_colline);
            return View(association);
        }

        // GET: associations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            association association = db.associations.Find(id);
            if (association == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", association.ID_colline);
            return View(association);
        }

        // POST: associations/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_association,ID_colline,NOM_association,TEL_association,DATE_association")] association association)
        {
            if (ModelState.IsValid)
            {
                db.Entry(association).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", association.ID_colline);
            return View(association);
        }

        // GET: associations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            association association = db.associations.Find(id);
            if (association == null)
            {
                return HttpNotFound();
            }
            return View(association);
        }

        // POST: associations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            association association = db.associations.Find(id);
            db.associations.Remove(association);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //POUR RAPPORT
        ////public ActionResult GetData()
        ////{

        ////    var result = (from A in db.associations
        ////                  join C in db.clients on A.ID_association equals C.ID_association
        ////                  join R in db.recoltes on C.ID_client equals R.ID_client
        ////                  group R by new { A.ID_association, A.NOM_association } into g
        ////                  select new
        ////                  {
        ////                      ID = g.Key.ID_association,
        ////                      name = g.Key.NOM_association,
        ////                      quantite = g.Sum(R => R.quantite)
        ////                  }).ToList();
        ////    return Json(result, JsonRequestBehavior.AllowGet);
        ////}
        public ActionResult GetData()
        {

            RecolteEntities context = new RecolteEntities();
            var list = context.recoltes.GroupBy(t => new { t.qualite, t.quantite,t.ID_recolte })
              .Select(i => new {
                  name = i.Key.qualite,
                  key = i.Key.ID_recolte,
                  count = i.Sum(w => w.quantite)
              }).ToList();

            return Json(list, JsonRequestBehavior.AllowGet);
        }

    }
}

WebApplicationrRecolte/Views/associations/Create.cshtml
@model WebApplicationrRecolte.Models.association

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="main-panel">
    <div class="container">

        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-3">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h2 class="text-white pb-2 fw-bold">
                            ASSOCIATION</
                            h2>
                    </div>
                    <div class="ml-md-auto py-2 py-md-0">
                        <!-- PAGE-HEADER -->
                        <div class="page-header">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">ASSOCIATION</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Ajouter
                                </li>
                            </ol>
                        </div>
                        <!-- PAGE-HEADER END -->
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Ajouter une nouvelle association</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label> Provinces :</label>
                        @Html.DropDownList("ID_province", null, "Selectionnez le province", htmlAttributes: new { @class = "form-control " })

                    </div>
                    <div class="form-group">
                        <label> Commune :</label>
                        @Html.DropDownList("ID_commune", new SelectList(new List<string>()), "Selectionnez le commune", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label> zone:</label>
                        @Html.DropDownList("ID_zone", new SelectList(new List<string>()), "Selectionnez zone", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label> colline:</label>
                        @Html.DropDownList("ID_colline", new SelectList(new List<string>()), "Selectionnez colline", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_colline, "", new { @class = "text-danger" })
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.NOM_association, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NOM_association, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NOM_association, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TEL_association, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TEL_association, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TEL_association, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DATE_association, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DATE_association, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DATE_association, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-success pull-right" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Retour", "Index")
            </div>


        </div>
    </div>

WebApplicationrRecolte/Views/associations/Delete.cshtml
@model WebApplicationrRecolte.Models.association

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>association</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOM_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TEL_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEL_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATE_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.colline.NOM_colline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.colline.NOM_colline)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplicationrRecolte/Views/associations/Details.cshtml
@model WebApplicationrRecolte.Models.association

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Details</h2>

<div>
    <h4>association</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOM_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TEL_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEL_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATE_association)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_association)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.colline.NOM_colline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.colline.NOM_colline)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_association }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationrRecolte/Views/associations/Edit.cshtml
@model WebApplicationrRecolte.Models.association

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>association</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_association)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_colline, "ID_colline", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_colline", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_colline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOM_association, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOM_association, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOM_association, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEL_association, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEL_association, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEL_association, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_association, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_association, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATE_association, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplicationrRecolte/Views/associations/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/_Default.cshtml";
}

<style>
    h2 {
        margin-bottom: 20px;
    }
</style>


<div class="row">
    <h2>Line Charts</h2>
    <div class="col-md-12" id="container"></div>
    <h2>pie Charts</h2>
    <div class="col-md-12" id="container2"></div>
    <h2>pie Charts</h2>
    <div class="col-md-12" id="container3"></div>

    <h2>cylindre Charts</h2>
    <div class="col-md-12" id="container1"></div>

</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg" style="width:1000px;">
        <!-- Modal -->
        <div class="modal-content  modal-lg">
            <div class="modal-header">
                <h4 class="modal-title"><span id="titre"></span></h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table id='mytable' class='table table-bordered table-striped table-hover table-condensed'>
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom  du client </th>
                                <th>Nom du produit </th>
                                <th>Quantite vendue</th>
                                <th>Montant paye</th>
                                <th>numero_facture</th>
                                <th>Mode de paiement</th>
                                <th>Solde rstante</th>
                                <th>Date de paiement</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
@section scripts
    {
    <script src="~/Scripts/Charts.js"></script>
}

WebApplicationrRecolte/Views/associations/Index1.cshtml
@model IEnumerable<WebApplicationrRecolte.Models.association>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="main-panel">
    <div class="container">

        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-3">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h2 class="text-white pb-2 fw-bold">
                            ASSOCIATION</
                            h2>
                    </div>
                    <div class="ml-md-auto py-2 py-md-0">
                        <!-- PAGE-HEADER -->
                        <div class="page-header">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">ASSOCIATION</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Liste
                                </li>
                            </ol>
                        </div>
                        <!-- PAGE-HEADER END -->
                    </div>
                </div>
            </div>
        </div>
        @{

            IEnumerable<WebApplicationrRecolte.Models.association> associations = ViewData["association"] as IEnumerable<WebApplicationrRecolte.Models.association>;
            IEnumerable<WebApplicationrRecolte.Models.historique_asscociation> historiques = ViewData["historique"] as IEnumerable<WebApplicationrRecolte.Models.historique_asscociation>;
        }
        @{

            List<int> IDassocition = new List<int>();
        }
        @foreach (WebApplicationrRecolte.Models.historique_asscociation iteme in historiques)
        {
            IDassocition.Add(iteme.ID_association);
        }
        <div class="container-fluid">
            <a href="@Url.Action("create","associations")" class=" btn btn-sm  btn-success pull-right  " style="margin-top:5px; margin-bottom:5px"><i class="fa fa-plus mr-2"></i>Nouvelle assocition</a>
            <table class="table table-bordered">
                <tr>
                    <th>
                        NOM
                    </th>
                    <th>
                        TEL
                    </th>
                    <th>
                        DATE DE CREATION
                    </th>
                    <th>
                        COLLINE
                    </th>
                    <th>
                        ETAT
                    </th>
                    
                </tr>

                @foreach (WebApplicationrRecolte.Models.association item in associations)
                {
                    
                        if (IDassocition.Contains(item.ID_association) == true)
                        {


                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NOM_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TEL_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DATE_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.colline.NOM_colline)
                                </td>



                                <td>
                                    Inactif
                                </td>
                               
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NOM_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TEL_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DATE_association)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.colline.NOM_colline)
                                </td>



                                <td>
                                    Actifs
                                </td>
                                
                            </tr>
                        }
                    }

                </table>
        </div>
    </div>

WebApplicationrRecolte/Views/associations/Indexe.cshtml
@model IEnumerable<WebApplicationrRecolte.Models.association>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/_Default.cshtml";
}
<div class="main-panel">
    <div class="container">

        <div class="panel-header bg-primary-gradient">
            <div class="page-inner py-3">
                <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                    <div>
                        <h2 class="text-white pb-2 fw-bold">
                            ASSOCIATION</
                            h2>
                    </div>
                    <div class="ml-md-auto py-2 py-md-0">
                        <!-- PAGE-HEADER -->
                        <div class="page-header">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">ASSOCIATION</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Liste
                                </li>
                            </ol>
                        </div>
                        <!-- PAGE-HEADER END -->
                    </div>
                </div>
            </div>
        </div>
        @{

            IEnumerable<WebApplicationrRecolte.Models.association> associations = ViewData["association"] as IEnumerable<WebApplicationrRecolte.Models.association>;
            IEnumerable<WebApplicationrRecolte.Models.historique_asscociation> historiques = ViewData["historique"] as IEnumerable<WebApplicationrRecolte.Models.historique_asscociation>;
        }
        @{

            List<int> IDassocition = new List<int>();
        }
        @foreach (WebApplicationrRecolte.Models.historique_asscociation iteme in historiques)
        {
            IDassocition.Add(iteme.ID_association);
        }
    <div class="container-fluid">
        <a href="@Url.Action("create","associations")" class=" btn btn-sm  btn-success pull-right  " style="margin-top:5px; margin-bottom:5px"><i class="fa fa-plus mr-2"></i>Nouvelle assocition</a>
        <table class="table table-bordered">
            <tr>
                <th>
                    NOM
                </th>
                <th>
                    TEL
                </th>
                <th>
                    DATE DE CREATION
                </th>
                <th>
                    COLLINE
                </th>
                <th>
                    ETAT
                </th>
                <th>
                    OPTIONS
                </th>

            </tr>

            @foreach (WebApplicationrRecolte.Models.association item in associations)
            {

                if (IDassocition.Contains(item.ID_association) != true)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NOM_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TEL_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DATE_association)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.colline.NOM_colline)
                        </td>
                        <td>
                            Actif
                        </td>
                        <td>
                            <div class="dropdown">
                                <span class="dropdown-toggle dropdown-bg btn btn-outline-primary" role="button" id="dropdownMenuButton5"
                                      data-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </span>
                                <div class="dropdown-menu dropdown-menu-right shadow-none" aria-labelledby="dropdownMenuButton5">
                                    @Html.ActionLink("Modifier", "Details", new { id = item.ID_association }, new { @class = "btn btn-sm btn-success " })
                                    @Html.ActionLink("Supprime", "Delete", new { id = item.ID_association }, new { @class = "btn btn-sm btn-danger" })
                                </div>
                            </div>
                        </td>

                    </tr>
                }

            }

        </table>

    </div>
    </div>