WebApplicationrRecolte/Controllers/clientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationrRecolte.Models;

namespace WebApplicationrRecolte.Controllers
{
    public class clientsController : Controller
    {
        private RecolteEntities db = new RecolteEntities();

        // GET: clients
        public ActionResult Index()
        {
            var clients = db.clients.Include(c => c.association).Include(c => c.colline);
            return View(clients.ToList());
        }

        // GET: clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: clients/Create
        public ActionResult Create()
        {
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association");
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline");
            return View();
        }

        // POST: clients/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_client,CNI,NOM_client,PRENOM_client,TEL_client,ID_colline,ID_association,DATE_insertion")] client client)
        {
            if (ModelState.IsValid)
            {
                db.clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", client.ID_association);
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", client.ID_colline);
            return View(client);
        }

        // GET: clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", client.ID_association);
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", client.ID_colline);
            return View(client);
        }

        // POST: clients/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_client,CNI,NOM_client,PRENOM_client,TEL_client,ID_colline,ID_association,DATE_insertion")] client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_association = new SelectList(db.associations, "ID_association", "NOM_association", client.ID_association);
            ViewBag.ID_colline = new SelectList(db.collines, "ID_colline", "NOM_colline", client.ID_colline);
            return View(client);
        }

        // GET: clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            client client = db.clients.Find(id);
            db.clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationrRecolte/Views/Partials/_Footer.cshtml
 @{
    ViewBag.Title = "_Footer";
}
@*<?php include VIEWPATH.'template/includes/sidebar_right.php';?>*@
@RenderPage("~/Views/Partials/_SidebarRight.cshtml")
		<!-- Custom template | don't include it in your project! -->
@*<?php include VIEWPATH.'template/includes/sidebar_settings.php';?>*@

@RenderPage("~/Views/Partials/_SidebarSetting.cshtml")
		<!-- End Custom template -->

@*</div>*@
	<footer class="footer" style="background-color:">
		<div class="container-fluid">
			<nav class="pull-left">
				<ul class="nav">
					<li class="nav-item">
						<a class="nav-link" href="#">
							Enregistrement de recoltes 
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							Cafe
						</a>
					</li>
				</ul>
			</nav>
			<div class="copyright ml-auto">
                @DateTime.Now.ToString("dddd, dd-MMMM-yyyy HH:mm:ss")
				Made with <a href="facebook.com/clauaine.ndayisaba">NDAYISABA Claudine</a>
			</div>				
		</div>
	</footer>
@*</div>


</div>*@
	<!--   Core JS Files   -->
	@*<script src="<?= base_url()?>assets/js/core/jquery.3.2.1.min.js"></script>
	<script src="<?= base_url()?>assets/js/core/popper.min.js"></script>
	<script src="<?= base_url()?>assets/js/core/bootstrap.min.js"></script>*@
    @Scripts.Render("~/Assets/js/core")
   @* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>*@

<!-- jQuery UI -->
	@*<script src="<?= base_url()?>assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>*@
	@Scripts.Render("~/Assets/js/plugin/jquery-ui-1.12.1.custom")
    @*<script src="<?= base_url()?>assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>*@
   @Scripts.Render("~/Assets/js/plugin/jquery-ui-touch-punch")
	<!-- jQuery Scrollbar -->
	@*<script src="<?= base_url()?>assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>*@
      @Scripts.Render("~/Assets/js/plugin/jquery-scrollbar")
	<!-- Moment JS -->
	@*<script src="<?= base_url()?>assets/js/plugin/moment/moment.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/moment")
	<!-- Chart JS -->
	@*<script src="<?= base_url()?>assets/js/plugin/chart.js/chart.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/chart.js")
	<!-- jQuery Sparkline -->

    @*<script src="<?= base_url()?>assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/jquery.sparkline")  
	<!-- Chart Circle -->
	@*<script src="<?= base_url()?>assets/js/plugin/chart-circle/circles.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/chart-circle")  
	<!-- Datatables -->

	@*<script src="<?= base_url()?>assets/js/plugin/datatables/datatables.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/datatables")  
	<!-- Bootstrap Notify -->
	@*<script src="<?= base_url()?>assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/bootstrap-notify")
	<!-- Bootstrap Toggle -->
	@*<script src="<?= base_url()?>assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/bootstrap-toggle")
	<!-- jQuery Vector Maps -->
	@*<script src="<?= base_url()?>assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/jqvmap")
	@*<script src="<?= base_url()?>assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/jqvmap/maps")
	<!-- Google Maps Plugin -->
	@*<script src="<?= base_url()?>assets/js/plugin/gmaps/gmaps.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/gmaps")
	<!-- Dropzone -->
	@*<script src="<?= base_url()?>assets/js/plugin/dropzone/dropzone.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/dropzone")
	<!-- Fullcalendar -->
	@*<script src="<?= base_url()?>assets/js/plugin/fullcalendar/fullcalendar.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/fullcalendar")
	<!-- DateTimePicker -->
	@*<script src="<?= base_url()?>assets/js/plugin/datepicker/bootstrap-datetimepicker.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/datepicker")
	<!-- Bootstrap Tagsinput -->
	@*<script src="<?= base_url()?>assets/js/plugin/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/bootstrap-tagsinput")
	<!-- Bootstrap Wizard -->
	@*<script src="<?= base_url()?>assets/js/plugin/bootstrap-wizard/bootstrapwizard.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/bootstrap-wizard")
	<!-- jQuery Validation -->
	@*<script src="<?= base_url()?>assets/js/plugin/jquery.validate/jquery.validate.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/jquery.validate")
	<!-- Summernote -->
	@*<script src="<?= base_url()?>assets/js/plugin/summernote/summernote-bs4.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/summernote")
	<!-- Select2 -->
	@*<script src="<?= base_url()?>assets/js/plugin/select2/select2.full.min.js"></script>*@
     @Scripts.Render("~/Assets/js/plugin/select2")
	<!-- Sweet Alert -->
	@*<script src="<?= base_url()?>assets/js/plugin/sweetalert/sweetalert.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/sweetalert")
	<!-- Owl Carousel -->
	@*<script src="<?= base_url()?>assets/js/plugin/owl-carousel/owl.carousel.min.js"></script>*@
    @Scripts.Render("~/Assets/js/plugin/owl-carousel")
	<!-- Magnific Popup -->
	@*<script src="<?= base_url()?>assets/js/plugin/jquery.magnific-popup/jquery.magnific-popup.min.js"></script>*@
     @Scripts.Render("~/Assets/js/plugin/jquery.magnific-popup")
	<!-- Atlantis JS -->
	@*<script src="<?= base_url()?>assets/js/atlantis.min.js"></script>*@
    @Scripts.Render("~/Assets/js")
	<!-- Atlantis DEMO methods, don't include it in your project! -->
	@*<script src="<?= base_url()?>assets/js/setting-demo.js"></script>
	<script src="<?= base_url()?>assets/js/demo.js"></script>*@
	<script>
		Circles.create({
			id:'circles-1',
			radius:45,
			value:60,
			maxValue:100,
			width:7,
			text: 5,
			colors:['#f1f1f1', '#FF9E27'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		Circles.create({
			id:'circles-2',
			radius:45,
			value:70,
			maxValue:100,
			width:7,
			text: 36,
			colors:['#f1f1f1', '#2BB930'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		Circles.create({
			id:'circles-3',
			radius:45,
			value:40,
			maxValue:100,
			width:7,
			text: 12,
			colors:['#f1f1f1', '#F25961'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		var totalIncomeChart = document.getElementById('totalIncomeChart').getContext('2d');

		var mytotalIncomeChart = new Chart(totalIncomeChart, {
			type: 'bar',
			data: {
				labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
				datasets : [{
					label: "Total Income",
					backgroundColor: '#ff9e27',
					borderColor: 'rgb(23, 125, 255)',
					data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
				}],
			},
			options: {
				responsive: true,
				maintainAspectRatio: false,
				legend: {
					display: false,
				},
				scales: {
					yAxes: [{
						ticks: {
							display: false //this will remove only the label
						},
						gridLines : {
							drawBorder: false,
							display : false
						}
					}],
					xAxes : [ {
						gridLines : {
							drawBorder: false,
							display : false
						}
					}]
				},
			}
		});

		$('#lineChart').sparkline([105,103,123,100,95,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: '#ffa534',
			fillColor: 'rgba(255, 165, 52, .14)'
		});
	</script>
@*</body>

<!-- Mirrored from demo.themekita.com/atlantis/livepreview/examples/demo1/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 24 Jul 2021 21:36:26 GMT -->
</html>*@

WebApplicationrRecolte/Views/Partials/_SidebarMenu.cshtml
@{
    ViewBag.Title = "_SidebarMenu";
}
<div class="sidebar sidebar-style-2">			
<div class="sidebar-wrapper scrollbar scrollbar-inner">
	<div class="sidebar-content">
		<div class="user">
            
			@*<?php 
			   $memb=$this->Model->readOne('membre', ['ID_MEMBRE'=> $this->session->userdata('memberid')]);

				?>*@
			<div class="avatar-sm float-left mr-2">
				@*<img src="<?= base_url('assets/photo/Profile/').$memb['IMAGE'];?>" alt="..." class="avatar-img rounded-circle">*@
			</div>
			<div class="info">
				<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
					<span>
						@*<h1><?= $this->session->userdata('prenom') ?></h1>*@
						<span class="user-level">Utilisateur</span>
						<span class="caret"></span>
					</span>
				</a>
				<div class="clearfix"></div>

				<div class="collapse in" id="collapseExample">
					<ul class="nav">
						<li>
							<a @*href="<?= base_url('membre/Membre/Profile')?>"*@>
								<span class="link-collapse">My Profile</span>
							</a>
						</li>
						<li>
							<a @*href="<?= base_url('membre/Membre/Profile')?>"*@>
								<span class="link-collapse">Edit Profile</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
        <ul class="nav nav-primary">
            <li class="nav-item active">
                <a href="#">
                    <i class="fas fa-home"></i>
                    <p>Dashboard</p>
                </a>

            </li>
            <li class="nav-item">
                <a data-toggle="collapse" href="#forms">
                    <i class="fas fa-users"></i>
                    <p>Associations</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="forms">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","associations")">
                                <span class="sub-item">Tous</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Indexe","associations")">
                                <span class="sub-item">Associations actifs</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","historique_asscociation")">
                                <span class="sub-item">Associations inactifs</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","employe_association")">
                                <span class="sub-item">Statistique et rapport</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">

                <a href="@Url.Action("Index","clients")">
                    <i class="fas fa-layer-group"></i>
                    <p>Clients</p>
                </a>
            </li>
            <li class="nav-item">
                <a data-toggle="collapse" href="#forms">
                    <i class="fas fa-users"></i>
                    <p>Stations de lavage</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="forms">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","employe_association")">
                                <span class="sub-item">Stations de lavage actifs</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","employe_station_lavage")">
                                <span class="sub-item">Stations de lavage inactifs</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","station_lavage")">
                                <span class="sub-item">Tous les deux</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item">

                <a href="@Url.Action("Index","recoltes")">
                    <i class="fas fa-layer-group"></i>
                    <p>Recoltes</p>
                </a>
            </li>

            <li class="nav-item">
                <a data-toggle="collapse" href="#tables">
                    <i class="fas fa-gifts"></i>
                    <p>Employes</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="tables">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","employe_association")">
                                <span class="sub-item">Employes des associtions</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","employe_station_lavage")">
                                <span class="sub-item">Employes des station de lavage</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="nav-item">
                <a href="@Url.Action("Index","qualites")">
                    <i class="fa fa-anchor"></i>
                    <p>Qualite</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#">
                    <i class="fas fa-info-circle"></i>
                    <p>Utilisateurs</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#">
                    <i class="fas fa-info-circle"></i>
                    <p>Profile</p>
                </a>
            </li>

            <li class="nav-item">
                <a href="#">
                    <i class="fas fa-sign-out-alt"></i>
                    <p> Logout</p>
                </a>
            </li>
        </ul>
	</div>
</div>
</div>

WebApplicationrRecolte/Views/Partials/_SidebarSetting.cshtml
@{
    ViewBag.Title = "_SidebarSetting";
}
<!-- Custom template Settings | don't include it in your project! -->
@*<div class="custom-template">
	<div class="title">Settings</div>
	<div class="custom-content">
		<div class="switcher">
			<div class="switch-block">
				<h4>Logo Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
					<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Navbar Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeTopBarColor" data-color="dark"></button>
					<button type="button" class="changeTopBarColor" data-color="blue"></button>
					<button type="button" class="changeTopBarColor" data-color="purple"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
					<button type="button" class="changeTopBarColor" data-color="green"></button>
					<button type="button" class="changeTopBarColor" data-color="orange"></button>
					<button type="button" class="changeTopBarColor" data-color="red"></button>
					<button type="button" class="changeTopBarColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeTopBarColor" data-color="dark2"></button>
					<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="purple2"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="green2"></button>
					<button type="button" class="changeTopBarColor" data-color="orange2"></button>
					<button type="button" class="changeTopBarColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Sidebar</h4>
				<div class="btnSwitch">
					<button type="button" class="selected changeSideBarColor" data-color="white"></button>
					<button type="button" class="changeSideBarColor" data-color="dark"></button>
					<button type="button" class="changeSideBarColor" data-color="dark2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Background</h4>
				<div class="btnSwitch">
					<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
					<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
					<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
					<button type="button" class="changeBackgroundColor" data-color="dark"></button>
				</div>
			</div>
		</div>
	</div>
	<div class="custom-toggle">
		<i class="flaticon-settings"></i>
	</div>
</div>*@
		<!-- End Custom template -->

<div class="custom-template">
	<div class="title">Settings</div>
	<div class="custom-content">
		<div class="switcher">
			<div class="switch-block">
				<h4>Logo Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
					<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Navbar Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeTopBarColor" data-color="dark"></button>
					<button type="button" class="changeTopBarColor" data-color="blue"></button>
					<button type="button" class="changeTopBarColor" data-color="purple"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
					<button type="button" class="changeTopBarColor" data-color="green"></button>
					<button type="button" class="changeTopBarColor" data-color="orange"></button>
					<button type="button" class="changeTopBarColor" data-color="red"></button>
					<button type="button" class="changeTopBarColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeTopBarColor" data-color="dark2"></button>
					<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="purple2"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="green2"></button>
					<button type="button" class="changeTopBarColor" data-color="orange2"></button>
					<button type="button" class="changeTopBarColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Sidebar</h4>
				<div class="btnSwitch">
					<button type="button" class="selected changeSideBarColor" data-color="white"></button>
					<button type="button" class="changeSideBarColor" data-color="dark"></button>
					<button type="button" class="changeSideBarColor" data-color="dark2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Background</h4>
				<div class="btnSwitch">
					<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
					<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
					<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
					<button type="button" class="changeBackgroundColor" data-color="dark"></button>
				</div>
			</div>
		</div>
	</div>
	<div class="custom-toggle">
         
		<i class="fa fa-cog" style="color:red"></i>
	</div>
</div>
		<!-- End Custom template -->